config/routes.rb
Rails.application.routes.draw do

  root to: 'static_pages#home'
  #app/views/static_pages/home.html.erbがTOPに表示されるように
  #Original is get 'static_pages/home'

  get 'signup',  to: 'users#new'
  #If you access /signup with Get method, do Users_controller's new action.
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  resources :users do
    member do
      get :followings
      get :followers
    end
  end
  #resources method はリソースの操作を可能にするURLを生成する
  #url is /users. action is depends on HTTP method.
  #Please use command 'rake routes' if you want to check route list. 
  resources :microposts
  resources :relationships, only: [:create, :destroy]
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
#ApplicationControllerというクラスを継承しているため、アクションに対応したviewを表示可能となる。 
#ここで対応しているのは views/static_pages/home.html.erb
#Controllerの名前の最後の部分は複数形にする.

  def home
    @micropost = current_user.microposts.build if logged_in?
    #ログインしている場合は、新しい@micropostインスタンスを作成して、user_idと紐付けている
    #current_user.microposts.build = Micropost.new(user_id: current_user:id)
    @feed_items = current_user.feed_items.includes(:user).order(created_at: :desc).page(params[:page]).per(10) if logged_in?
  end
  
end

app/views/static_pages/home.html.erb
<% if logged_in? %>
  <div class="row">
    <aside class="col-md-4 user_profile_space user_profile_expand">
      <section class="user_info">
        <%= render 'shared/user_info' %>
      </section>
      <section class="micropost_form">
        <%= render 'shared/micropost_form' %>
      </section>
    </aside>
    <div class="col-md-8">
      <h3>タイムライン</h3>
      <%= render 'shared/feed' %>
    </div>
  </div>
<% else %>
  <div class="center jumbotron">
    <h1>Welcome to the Microposts</h1>
    <%= link_to "新規登録", signup_path, class: "btn btn-lg btn-primary" %>
    <%= link_to "ログイン", login_path, class: "btn btn-lg btn-primary" %>
  </div>
<% end %>