config/routes.rb
Rails.application.routes.draw do

  root to: 'static_pages#home'
  #app/views/static_pages/home.html.erbがTOPに表示されるように
  #Original is get 'static_pages/home'

  get 'signup',  to: 'users#new'
  #If you access /signup with Get method, do Users_controller's new action.
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  resources :users do
    member do
      get :followings
      get :followers
    end
  end
  #resources method はリソースの操作を可能にするURLを生成する
  #url is /users. action is depends on HTTP method.
  #Please use command 'rake routes' if you want to check route list. 
  resources :microposts
  resources :relationships, only: [:create, :destroy]
end

app/models/user.rb
class User < ActiveRecord::Base
#model's name is always singular and start from upper case letter
#ActiveRecord::Baseというクラスを継承することで、DBのTableを利用可能

    before_save { self.email = self.email.downcase }
    #emailを小文字に変更。before_saveはコールバックと呼ばれ、データの保存が行われる前にmethodを実行
        validates :name, presence: true, length: { in: 2..20 }
        VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
        #emailの正規表現パターンを定義
        validates :email, presence: true, length: { in: 2..255 },
                        format: { with: VALID_EMAIL_REGEX },
                        uniqueness: { case_sensitive: false }
        #指定した正規表現パターンに一致するかvalidate

    has_secure_password
    #Userモデルに下記の機能を追加
    #1.DBにハッシュ化されたpassword_digestを保存
    #2.passwordとpassword_confirmationをモデルに追加し、パスワードの確認が一致するか検証する
    #3.パスワードが正しい時に、ユーザーを返すauthenticate methodを提供する

    validates :address, presence: true, length: { maximum: 100 } , on: :update
    validates :profile, presence: true, length: { maximum: 100 } , on: :update
    
    has_many :microposts
    #投稿に紐付いている。複数の投稿が1ユーザーに紐づく。
    has_many :following_relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
    #user.following_relationshipsでuserがフォローしているrelationshipの集まりを取得. follower_idとfollowed_id(user_id)の関連.
    has_many :following_users, through: :following_relationships, source: :followed
    #following_relationships経由で、フォローしているユーザーの集まりを取得。
    has_many :follower_relationships, class_name:  "Relationship", foreign_key: "followed_id", dependent: :destroy
    #userがフォローされているrelationshipの集まりを取得
    has_many :follower_users, through: :follower_relationships, source: :follower
    #userがフォローされているユーザーの集まりを取得
    
    # 他のユーザーをフォローする
    def follow(other_user)
        following_relationships.find_or_create_by(followed_id: other_user.id)
        #find_or_create_by methodは因数のパラメータと一致するものを一見取得し、存在する場合はそのオブジェクトを返し、ない場合は作成し保存する
    end
    
    # フォローしているユーザーをアンフォローする
    def unfollow(other_user)
        following_relationship = following_relationships.find_by(followed_id: other_user.id)
        following_relationship.destroy if following_relationship
    end
    
    # あるユーザーをフォローしているかどうか？
    def following?(other_user)
        following_users.include?(other_user)
    end
    
    def feed_items
        Micropost.where(user_id: following_user_ids + [self.id])
    end
        
    mount_uploader :usericon, UsericonUploader
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    user_find
    @microposts = @user.microposts.order(created_at: :desc).page(params[:page]).per(10)
    #ユーザーに紐付いたmicropostを作成日時が新しいモノから取得
  end
 
  def new
    @user = User.new
    #Userクラスの新しいインスタンスを作成して、UsersControllerのインスタンス変数@userに代入
  end
  
  def create
  #postで送信されたparamsを元に@userデータを作成
    @user = User.new(user_params)
      if @user.save
        flash.now[:success] = "Welcome to the Sample application!"
        #Key is :success and value is Welcome to--
        session[:user_id] = @user.id
        redirect_to @user
        #redirect_to user_path(@user)
      else
        render 'new'
      end
  end
  
  def edit
    user_find
    check_login
  end
  
  def update
    user_find
    check_login
    if @user.update_attributes(user_params)
      flash[:success] = "変更を保存しました"
      redirect_to @user
    else
      flash.now[:danger] = "保存に失敗しました"
      render 'edit'
    end
  end
  
  def followings
    @user = User.find(params[:id])
    @following = @user.following_users.order(created_at: :desc).page(params[:page]).per(10)
  end
  
  def followers
    @user = User.find(params[:id])
    @follower = @user.follower_users.order(created_at: :desc).page(params[:page]).per(10)
  end
  
  private

  def user_find
    @user = User.find(params[:id])
  end
  
  def check_login
    if(current_user != @user)
      redirect_to root_path
    end
  end
  
  def user_params
    params.require(:user).permit(:name,:email,:password,:password_confirmation,:address,:profile,:usericon,:usericon_cache)
  end

end

app/helpers/users_helper.rb
module UsersHelper
#ヘルパーはモデルの情報を受け取って表示用の出力（HTMLタグの表示、テキストの出力）を行うメソッドを入れるモジュール
  def gravatar_for(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    #メールアドレスからGravatarの画像用のURLを生成
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
    #<img>タグを出力
  end
end

app/views/users/_follow.html.erb
<%= form_for(current_user.following_relationships.build, remote: true) do |f| %>
<%# remote: trueによってajaxでrequestが行われ、jsでページの一部が切り替わる %>
  <div><%= hidden_field_tag :followed_id, @user.id %></div>
  <%# hidden_field_tagによって、フォローするユーザーの値をidとしてもつタグが作成される %>
  <%= f.submit "Follow", class: "btn btn-primary" %>
<% end %>

app/views/users/_follow_form.html.erb
<% if current_user != @user %>
  <div id="follow_form">
  <% if current_user.following?(@user) %>
    <%= render 'unfollow' %>
  <% else %>
    <%= render 'follow' %>
  <% end %>
  </div>
<% end %>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.following_relationships.find_by(followed_id: @user.id),
             html: { method: :delete },
             remote: true) do |f| %>
  <%= f.submit "Unfollow", class: "btn" %>
<% end %>

app/views/users/edit.html.erb
<h1>登録情報を編集する</h1>

<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <%= form_for(@user) do |f| %>
            <%= render 'shared/error_messages', object: f.object %>
            <%# object=@user %>
        
            <%= f.label :name,"名前" %>
            <%= f.text_field :name, :placeholder => "20文字以内で入力してください", class:'form-control' %>
            
            <%= f.label :email,"メールアドレス" %>
            <%= f.text_field :email, :placeholder => "255文字以内で入力してください", class:'form-control' %>
            
            <%= f.label :profile,"プロフィール" %>
            <%= f.text_field :profile, :placeholder => "100文字以内で入力してください", class:'form-control' %>
            
            <%= f.label :address,"住所" %>
            <%= f.text_field :address, :placeholder => "100文字以内で入力してください", class:'form-control' %>
            
            <%= f.label :usericon,"プロフィール画像" %>
            <%= f.file_field :usericon %>
            <%= f.hidden_field :usericon_cache %>

            <%= f.submit "更新する", class:"btn btn-large btn-primary" %>
            <%# <input type="submit" name="Create my account" value="Create User" /> %>
        <% end %>
    </div>
</div>

app/views/users/followers.html.erb
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <% if @user.usericon? %>
            <div class="usericon">
            <%= image_tag @user.usericon.thumb.url %>
            </div>
        <% else %>
            <%= gravatar_for(@user,size:50) %>
        <% end %>
        <%= @user.name %>
        <%# ログインされていなかったら実行されない %>
        <%# current_user.idでも良い %>
      </h1>
      <%= link_to "編集する", edit_user_path(current_user) if logged_in? && (current_user == @user) %><br>
      <%# ログインしていてかつ現在のユーザー=@userの場合に表示 %>
      <%= link_to "フォロー", followings_user_path(@user) if logged_in? %> | 
      <%= link_to "フォロワー", followers_user_path(@user) if logged_in? %>
    </section>
  </aside>
  <div class="col-md-8">
    <h1>フォロワー</h1>
    <% @follower.each_with_index do |user,i| %>
      <hr class="style-one">
      <% if user.usericon? %>
        <%= link_to image_tag(user.usericon.thumb.url), user_path(user) %>
      <% else %>
        <%= link_to gravatar_for(user, size: 50), user_path(user) %>
      <% end %>
      ユーザー名: <%= link_to user.name, user_path(user) %>
      <% if i == @follower.length - 1 %>
        <hr class="style-one">
      <% end %>
     <%= paginate @follower %>
    <% end %>
  </div>
</div>

app/views/users/followings.html.erb
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <% if @user.usericon? %>
            <div class="usericon">
            <%= image_tag @user.usericon.thumb.url %>
            </div>
        <% else %>
            <%= gravatar_for(@user,size:50) %>
        <% end %>
        <%= @user.name %>
        <%# ログインされていなかったら実行されない %>
        <%# current_user.idでも良い %>
      </h1>
      <%= link_to "編集する", edit_user_path(current_user) if logged_in? && (current_user == @user) %><br>
      <%# ログインしていてかつ現在のユーザー=@userの場合に表示 %>
      <%= link_to "フォロー", followings_user_path(@user) if logged_in? %> | 
      <%= link_to "フォロワー", followers_user_path(@user) if logged_in? %>
    </section>
  </aside>
  <div class="col-md-8">
    <h1>フォロー</h1>
    <% @following.each_with_index do |user,i| %>
      <hr class="style-one">
      <% if user.usericon? %>
        <%= link_to image_tag(user.usericon.thumb.url), user_path(user) %>
      <% else %>
        <%= link_to gravatar_for(user, size: 50), user_path(user) %>
      <% end %>
      ユーザー名: <%= link_to user.name, user_path(user) %>
      <% if i == @following.length - 1 %>
        <hr class="style-one">
      <% end %>
      <%= paginate @following %>
    <% end %>
  </div>
</div>

app/views/users/new.html.erb
<%# Users#new %>

<h1>Sign up</h1>

<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <%= form_for(@user) do |f| %>
            <%= render 'shared/error_messages', object: f.object %>
            <%# object=@user %>
        
            <%= f.label :name,"名前" %>
            <%= f.text_field :name, :placeholder => "20文字以内で入力してください", class:'form-control' %>
            
            <%= f.label :email,"メールアドレス" %>
            <%= f.text_field :email, :placeholder => "255文字以内で未登録のメールアドレスを入力してください", class:'form-control' %>

            <%= f.label :password, "パスワード" %>
            <%= f.password_field :password, class:'form-control' %>
            <%# f.password_fieldでは文字が伏せ字になる %>

            <%= f.label :password_confirmation, "パスワード(確認用)" %>
            <%= f.password_field :password_confirmation, class:'form-control' %>
            
            <%= f.submit "Create my account", class:"btn btn-large btn-primary" %>
            <%# <input type="submit" name="Create my account" value="Create User" /> %>
        <% end %>
    </div>
</div>

app/views/users/show.html.erb
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <% if @user.usericon? %>
            <div class="usericon">
            <%= image_tag @user.usericon.thumb.url %>
            </div>
        <% else %>
            <%= gravatar_for @user %>
        <% end %>
        <%= @user.name %>
        <%# ログインされていなかったら実行されない %>
        <%# current_user.idでも良い %>
      </h1>
      <%= link_to "編集する", edit_user_path(current_user) if logged_in? && (current_user == @user) %><br>
      <%# ログインしていてかつ現在のユーザー=@userの場合に表示 %>
      <%= link_to "フォロー", followings_user_path(@user) if logged_in? %> | 
      <%= link_to "フォロワー", followers_user_path(@user) if logged_in? %>
    </section>
    <section>
      <%= render 'follow_form' if logged_in? %>
    </section>
  </aside>
  <div class="col-md-8">
        <% if @user.microposts.any? %>
          <h3>投稿一覧 (<%= @user.microposts.count %>)</h3>
          <ol class="microposts">
          <%= render @microposts %>
          <%# = render partial: 'microposts/micropost', collection: @microposts %>
          <%= paginate @microposts %>
        </ol>
      <% end %>
  </div>
</div>