config/routes.rb
Rails.application.routes.draw do

  root to: 'static_pages#home'
  #app/views/static_pages/home.html.erbがTOPに表示されるように
  #Original is get 'static_pages/home'

  get 'signup',  to: 'users#new'
  #If you access /signup with Get method, do Users_controller's new action.
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  resources :users do
    member do
      get :followings
      get :followers
    end
  end
  #resources method はリソースの操作を可能にするURLを生成する
  #url is /users. action is depends on HTTP method.
  #Please use command 'rake routes' if you want to check route list. 
  resources :microposts
  resources :relationships, only: [:create, :destroy]
end

app/models/micropost.rb
class Micropost < ActiveRecord::Base
  belongs_to :user
  #userに関連付けされている。それぞれの投稿は1ユーザーに紐づく。
  
  validates :user_id, presence: true
  validates :content, presence: true, length: { maximum: 140 }
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
    before_action :logged_in_user, only: [:create]
    #application_controllerのlogged_in_user methodでログインしていない場合は/loginにリダイレクト

    def create
        @micropost = current_user.microposts.build(micropost_params)
        if @micropost.save
            flash[:success] = "メッセージは保存されました"
            redirect_to root_url
        else
            @feed_items = current_user.feed_items.includes(:user).order(created_at: :desc).page(params[:page]).per(10)
            render 'static_pages/home'
        end
    end
    
    def destroy
        @micropost = current_user.microposts.find_by(id: params[:id])
        #投稿がユーザーのものでない場合はルートへリダイレクト
        return redirect_to root_url if @micropost.nil?
        @micropost.destroy
        flash[:success] = "投稿を削除しました"
        redirect_to request.referrer || root_url
        #referrerへ遷移
    end
    
    private
    
    def micropost_params
        params.require(:micropost).permit(:content)
    end
    
end

app/views/microposts/_micropost.html.erb
<li id="micropost-<%= micropost.id %>">
  <%# ユーザーアイコンがある場合は、ユーザーアイコンを表示する %>
  <% if micropost.user.usericon? %>
    <div class="usericon">
    <%= image_tag micropost.user.usericon.thumb.url %>
    </div>
  <% else %>
    <%= gravatar_for(micropost.user,size:50) %>
  <% end %>
  <span class="user"><%= link_to micropost.user.name, micropost.user %></span>
  <span class="content"><%= micropost.content %></span>
  <span class="timestamp">
    <%= time_ago_in_words(micropost.created_at) %>前に投稿
    <% if current_user == micropost.user %>
      <%= link_to "削除する", micropost_path(micropost), method: :delete, data: { confirm: "本当に削除しますか?" } %>
    <% end %>
  </span>
</li>