config/routes.rb
Rails.application.routes.draw do

  root to: 'static_pages#home'
  #app/views/static_pages/home.html.erbがTOPに表示されるように
  #Original is get 'static_pages/home'

  get 'signup',  to: 'users#new'
  #If you access /signup with Get method, do Users_controller's new action.
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  resources :users do
    member do
      get :followings
      get :followers
    end
  end
  #resources method はリソースの操作を可能にするURLを生成する
  #url is /users. action is depends on HTTP method.
  #Please use command 'rake routes' if you want to check route list. 
  resources :microposts
  resources :relationships, only: [:create, :destroy]
end

app/views/layouts/_header.html.erb
<%# Header partial %>
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
        <%= link_to "Microposts", root_path, id: "logo" %>
      </div>
    <%# link_to リンク名, リンクURL %>
      <div class="collapse navbar-collapse">
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to "Home",root_path %></li>
          <li><%= link_to "Help",'#' %></li>
          <% if logged_in? %>
            <li><%= link_to "Users", '#' %></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Account <b class="caret"></b>
                <!-- caret=逆三角形 -->
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Profile", current_user %></li>
                <%# current_user methodはSessionsHelperで設定 %>
                <li><%= link_to "Setting", edit_user_path(current_user) %></li>
                <li class="divider"></li>
                <li><%= link_to "Log out", logout_path, method: "delete" %></li>
              </ul>
            </li>
            <% else %>
              <li><%= link_to "Log in", login_path %></li>
            <% end %>
        </ul>
      </div>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<%# microposts全体で使用するHTMLのレイアウト %>
<html>
<head>
  <title>Microposts</title>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
</head>
<body>
    <%= render 'layouts/header' %>
    <%# headerパーシャルを読み込む %>
    
    <div class="container">
      <% flash.each do |message_type, message| %>
      <%# message_type is hash key and message is a value %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      
      <%= yield %>
      <%# Controllerが処理した内容を埋め込む %>
    </div>
</body>
</html>